# Generated by Django 5.0.14 on 2026-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=200),
        ),
    ]
