# Generated by Django 5.0.14 on 2026-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_seed_career_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertrack',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default='easy', max_length=50),
        ),
    ]
