# Generated by Django 5.0.14 on 2026-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_alter_careertrack_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
    ]
