# Generated by Django 5.0.14 on 2026-05-29 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_simulation_add_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careertrack',
            name='company',
            field=models.CharField(default='TechSprint Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='domain',
            field=models.CharField(choices=[('tech', 'Technology'), ('design', 'Design'), ('data', 'Data'), ('hr', 'HR & Operations')], default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='salary_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('career_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='simulations.careertrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'career_track')},
            },
        ),
    ]
