# Generated by Django 5.0.14 on 2026-05-27 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('code_quality_score', models.IntegerField(blank=True, null=True)),
                ('communication_score', models.IntegerField(blank=True, null=True)),
                ('problem_solving_score', models.IntegerField(blank=True, null=True)),
                ('time_management_score', models.IntegerField(blank=True, null=True)),
                ('completeness_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('what_a_senior_would_say', models.TextField(blank=True)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('file_urls', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('coding', 'Coding'), ('design', 'Design'), ('report', 'Report'), ('meeting', 'Meeting'), ('bug_fix', 'Bug Fix'), ('code_review', 'Code Review'), ('testing', 'Testing'), ('devops', 'DevOps'), ('documentation', 'Documentation')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('deadline_hours', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='pending', max_length=20)),
                ('ai_generated_context', models.JSONField(blank=True, null=True)),
                ('client_context', models.TextField(blank=True)),
                ('expected_deliverable', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
